_wandb:
    value:
        cli_version: 0.25.0
        e:
            mefeon96bug0xozdcagdjin0krbeqxb4:
                codePath: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                codePathLocal: lob_simulation.ipynb
                cpu_count: 24
                cpu_count_logical: 48
                disk:
                    /:
                        total: "1966736678912"
                        used: "35899252736"
                email: ahnb24@gmail.com
                executable: /usr/local/bin/python3.10
                host: amirhessam
                memory:
                    total: "67374432256"
                os: Linux-6.17.0-20-generic-x86_64-with-glibc2.39
                program: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                python: CPython 3.10.11
                root: /home/amirhessam/Uni/Term 1/ABM/lob
                startedAt: "2026-05-02T16:38:38.466710Z"
                writerId: mefeon96bug0xozdcagdjin0krbeqxb4
        m: []
        python_version: 3.10.11
        t:
            "3":
                - 2
                - 14
            "4": 3.10.11
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": linux-x86_64
ALPHA:
    value: 0.20704533048572357
D:
    value: 20
EPS_DECAY:
    value: 0.9845745164551551
EPS_MIN:
    value: 0.02490250864131795
EPS0:
    value: 0.5924381906451132
GAMMA:
    value: 0.9595886693822004
L:
    value: 100
LAMBDA_HOLD:
    value: 0.0012271508178547154
LAMBDA_INV:
    value: 0.0022413080979788213
"N":
    value: 500
Pf:
    value: 10000
R:
    value: 5
S:
    value: 1500
TE:
    value: 15000
deltaP:
    value: 1
save_path:
    value: null
tc:
    value: 500
w:
    value: 0.8762888950771449
