_wandb:
    value:
        cli_version: 0.25.0
        e:
            frtstwc306ci99swf0k9tzhom3qzuvtq:
                codePath: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                codePathLocal: lob_simulation.ipynb
                cpu_count: 24
                cpu_count_logical: 48
                disk:
                    /:
                        total: "1966736678912"
                        used: "35891236864"
                email: ahnb24@gmail.com
                executable: /usr/local/bin/python3.10
                host: amirhessam
                memory:
                    total: "67374432256"
                os: Linux-6.17.0-20-generic-x86_64-with-glibc2.39
                program: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                python: CPython 3.10.11
                root: /home/amirhessam/Uni/Term 1/ABM/lob
                startedAt: "2026-05-02T16:28:35.928307Z"
                writerId: frtstwc306ci99swf0k9tzhom3qzuvtq
        m: []
        python_version: 3.10.11
        t:
            "3":
                - 2
                - 14
            "4": 3.10.11
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": linux-x86_64
ALPHA:
    value: 0.016343290554325138
D:
    value: 5
EPS_DECAY:
    value: 0.9300121215556982
EPS_MIN:
    value: 0.012580440717461928
EPS0:
    value: 0.8750660631978193
GAMMA:
    value: 0.9388295843918784
L:
    value: 100
LAMBDA_HOLD:
    value: 0.026359838546915256
LAMBDA_INV:
    value: 0.004090785161667171
"N":
    value: 1000
Pf:
    value: 10000
R:
    value: 5
S:
    value: 1500
TE:
    value: 10000
deltaP:
    value: 1
save_path:
    value: null
tc:
    value: 500
w:
    value: 0.7712833126165459
