_wandb:
    value:
        cli_version: 0.25.0
        e:
            1wi9z3wohg40ivrrk562z2la6ngvije2:
                codePath: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                codePathLocal: lob_simulation.ipynb
                cpu_count: 24
                cpu_count_logical: 48
                disk:
                    /:
                        total: "1966736678912"
                        used: "35891830784"
                email: ahnb24@gmail.com
                executable: /usr/local/bin/python3.10
                host: amirhessam
                memory:
                    total: "67374432256"
                os: Linux-6.17.0-20-generic-x86_64-with-glibc2.39
                program: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                python: CPython 3.10.11
                root: /home/amirhessam/Uni/Term 1/ABM/lob
                startedAt: "2026-05-02T16:31:46.792090Z"
                writerId: 1wi9z3wohg40ivrrk562z2la6ngvije2
        m: []
        python_version: 3.10.11
        t:
            "3":
                - 2
                - 14
            "4": 3.10.11
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": linux-x86_64
ALPHA:
    value: 0.04326411127570311
D:
    value: 10
EPS_DECAY:
    value: 0.923678452796364
EPS_MIN:
    value: 0.05439023586114145
EPS0:
    value: 0.9902515923452464
GAMMA:
    value: 0.9689779670956206
L:
    value: 100
LAMBDA_HOLD:
    value: 0.008699123102052661
LAMBDA_INV:
    value: 0.029765830186925225
"N":
    value: 1000
Pf:
    value: 10000
R:
    value: 5
S:
    value: 1500
TE:
    value: 15000
deltaP:
    value: 1
save_path:
    value: null
tc:
    value: 2000
w:
    value: 0.7122378200923458
