_wandb:
    value:
        cli_version: 0.25.0
        e:
            u2jvw0pa1zt3jg82ezor5rc50z1q9edm:
                codePath: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                codePathLocal: lob_simulation.ipynb
                cpu_count: 24
                cpu_count_logical: 48
                disk:
                    /:
                        total: "1966736678912"
                        used: "35893559296"
                email: ahnb24@gmail.com
                executable: /usr/local/bin/python3.10
                host: amirhessam
                memory:
                    total: "67374432256"
                os: Linux-6.17.0-20-generic-x86_64-with-glibc2.39
                program: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                python: CPython 3.10.11
                root: /home/amirhessam/Uni/Term 1/ABM/lob
                startedAt: "2026-05-02T16:35:02.122120Z"
                writerId: u2jvw0pa1zt3jg82ezor5rc50z1q9edm
        m: []
        python_version: 3.10.11
        t:
            "3":
                - 2
                - 14
            "4": 3.10.11
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": linux-x86_64
ALPHA:
    value: 0.05445180629753337
D:
    value: 10
EPS_DECAY:
    value: 0.9718912321598908
EPS_MIN:
    value: 0.029667396930113193
EPS0:
    value: 0.7120261040647915
GAMMA:
    value: 0.9251175739095192
L:
    value: 100
LAMBDA_HOLD:
    value: 0.016461875604355733
LAMBDA_INV:
    value: 0.0019811398282027137
"N":
    value: 1000
Pf:
    value: 10000
R:
    value: 5
S:
    value: 1500
TE:
    value: 15000
deltaP:
    value: 1
save_path:
    value: null
tc:
    value: 1500
w:
    value: 0.6876496923388469
