_wandb:
    value:
        cli_version: 0.25.0
        e:
            t4zbs3klvniuccat2amhm771cmfi6b29:
                codePath: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                codePathLocal: lob_simulation.ipynb
                cpu_count: 24
                cpu_count_logical: 48
                disk:
                    /:
                        total: "1966736678912"
                        used: "35840045056"
                email: ahnb24@gmail.com
                executable: /usr/local/bin/python3.10
                host: amirhessam
                memory:
                    total: "67374432256"
                os: Linux-6.17.0-20-generic-x86_64-with-glibc2.39
                program: /home/amirhessam/Uni/Term 1/ABM/lob/lob_simulation.ipynb
                python: CPython 3.10.11
                root: /home/amirhessam/Uni/Term 1/ABM/lob
                startedAt: "2026-05-02T16:24:16.567525Z"
                writerId: t4zbs3klvniuccat2amhm771cmfi6b29
        m: []
        python_version: 3.10.11
        t:
            "3":
                - 2
                - 14
            "4": 3.10.11
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": linux-x86_64
ALPHA:
    value: 0.02350008481550112
D:
    value: 5
EPS_DECAY:
    value: 0.9741974383656968
EPS_MIN:
    value: 0.010128289570222196
EPS0:
    value: 0.1157800323835228
GAMMA:
    value: 0.8354990162864461
L:
    value: 300
LAMBDA_HOLD:
    value: 0.032222689044546594
LAMBDA_INV:
    value: 0.020096607424781854
"N":
    value: 200
Pf:
    value: 10000
R:
    value: 5
S:
    value: 500
TE:
    value: 5000
deltaP:
    value: 1
save_path:
    value: null
tc:
    value: 1500
w:
    value: 0.4529317026323415
